RK1 frontend
frontend-park-mail-ru/2023_2_fanaty_elki pull request #3
Opened 2023-10-05 14:03 UTC by kek-flip

2023-10-05 20:44 UTC, LDK28 requested changes

2023-10-05 20:44 UTC, LDK28 commented on src/modules/ajax.js
Походы в сеть надо вынести в ajax, чтобы у вас были безопасные функции, куда вы передаете просто контекст, чтобы, ну и плюс если вдруг поменяются урлы, вы быстро могли их подменить

2023-10-05 20:44 UTC, LDK28 commented on src/utils/safe.js
Как-будто решение вынести функцию валидации в utils было хорошим решением, верните, пожалуйста

2023-10-06 10:17 UTC, kek-flip commented on public/index.js
> +window.backendURL = 'http://127.0.0.1:3000';
В backendURL указал адрес localhost
Перед тем, как окончательно мержить, не забудь поменять на адрес прода

2023-10-06 11:05 UTC, LDK28 approved these changes

2023-10-06 11:05 UTC, merged