Ajax refactoring
frontend-park-mail-ru/2023_2_fanaty_elki pull request #8
Opened 2023-10-19 13:21 UTC by wizardOfOz21

2023-10-20 00:24 UTC, LDK28 requested changes

2023-10-20 00:24 UTC, LDK28 commented on public/index.js
> +await userModel.auth(); // сюда ошибки не поднимаются
Такие комменты лучше не оставлять в коде :)

2023-10-20 00:24 UTC, LDK28 commented on src/models/UserModel/UserModel.js
> +            // console.log(e); // сюда стекает всё: ошибки сети, отрицательные ответы сервера,
аналогично

2023-10-20 00:24 UTC, LDK28 commented on src/models/UserModel/UserModel.js
> +            // console.log(e); // сюда стекает всё: ошибки сети, отрицательные ответы сервера,
и туть

2023-10-20 00:24 UTC, LDK28 commented on src/models/UserModel/UserModel.js
> +            throw e;
ловить ошибку, чтобы снова ее бросить - нелогично. Либо обработка ошибки, либо ловите ее где-то выше

2023-10-20 00:24 UTC, LDK28 commented on src/models/UserModel/UserModel.js
> +            // console.log(e); // сюда стекает всё: ошибки сети, отрицательные ответы сервера
Есть такая штука [toastify](https://www.npmjs.com/package/react-toastify), можете попробовать реализовать ее сами, ну а пока просто логируйте

2023-10-20 00:24 UTC, LDK28 commented on src/modules/api.js
> +        throw Error('unexpected error');
Статусы ошибок лучше вынести в константы

2023-10-20 00:24 UTC, LDK28 commented on src/modules/api.js
> +    if (!response.ok) {
Лучше проверять статус, так как если вы ждете 200, а приходит 201, то это нехорошо

2023-10-24 21:03 UTC, kek-flip commented on src/models/UserModel/UserModel.js
> +            throw e;
Ошибка выкидывается на верх - ее должен обрабатывать контроллер

2023-10-24 21:05 UTC, kek-flip commented on src/models/UserModel/UserModel.js
> +            // console.log(e); // сюда стекает всё: ошибки сети, отрицательные ответы сервера,
Заменил на лаконичные TODO

2023-10-24 21:56 UTC, kek-flip approved these changes

2023-10-24 21:59 UTC, merged